# Generated by Django 4.1.3 on 2023-10-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_remove_book_author_remove_book_link_and_more'),
        ('appmain', '0003_auto_20231027_2349'),
    ]

    operations = [
    ]
