# Generated by Django 4.1.3 on 2023-10-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_alter_book_link'),
        ('appmain', '0004_merge_20231027_2350'),
    ]

    operations = [
    ]
